targets:
  $default:
    builders:
      asset_enum|localize_enum|localize_cubit|create_hive:
        enabled: true

builders:
  auto_save:
    target: ":auto_save"
    import: "package:code_generation/builder.dart"
    builder_factories: ["autoSave"]
    build_extensions: { ".dart": [".local.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
  asset_enum:
    target: ":asset_enum"
    import: "package:code_generation/builder.dart"
    builder_factories: ["assetEnum"]
    build_extensions: { ".dart": [".local.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
  create_hive:
    target: ":create_hive"
    import: "package:code_generation/builder.dart"
    builder_factories: ["hiveJsonBuilder"]
    build_extensions: {".dart": [".hive.g.dart"]}
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
    build_to: cache
  localize_enum:
    target: ":localize_enum"
    import: "package:code_generation/builder.dart"
    builder_factories: ["localizationEnum"]
    build_extensions: { ".dart": [".enum.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
