name: code_generation
description: Code generator for localize enum that makes the use of enums much better.
version: 0.0.1+28
publish_to: 'none'
homepage: https://www.raehealth.com

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  analyzer:
  build:
  build_config:
  code_generation_annotation:
    path: ../code_generation_annotation
    # git:
    #   url: https://github.com/RAE-Health/localize_enum.git
    #   path: packages/localize_enum_annotation
  source_gen: