name: code_generation
description: Code generator for localize enum that makes the use of enums much better.
version: 0.0.3+117
publish_to: 'none'
homepage: https://www.raehealth.com

environment:
  sdk: ">=2.16.2 <3.0.0" #Dart SDK 2022-04-02
  flutter: ">=2.10.4"

dependencies:
  analyzer:
  build:
  build_config:
  code_generation_annotation:
    git:
      url: git@github.com:RAE-Health/code_generation.git
      path: packages/code_generation_annotation
  source_gen: