name: code_generation
description: Code generator for localize enum that makes the use of enums much better.
version: 0.0.3+105
publish_to: 'none'
homepage: https://www.raehealth.com

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  analyzer:
  build:
  build_config:
  code_generation_annotation:
    # path: ../code_generation_annotation
    git:
      url: https://github.com/RAE-Health/code_generation.git
      path: packages/code_generation_annotation
  source_gen: