name: code_generation_annotation
description: Annotations for the localize_enum code generator package.
version: 0.0.3+106
homepage: https://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0" #Dart SDK 2021-12-20
  flutter: ">=2.8.1"

dependencies:
  meta: ^1.7.0
