name: code_generation_annotation
description: Annotations for the localize_enum code generator package.
version: 0.0.3+115
homepage: https://www.raehealth.com
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0" #Dart SDK 2022-02-18
  flutter: ">=2.10.2"

dependencies:
  meta: ^1.7.0
